# Generated by Django 3.2 on 2022-10-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
