# Generated by Django 3.2 on 2022-10-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='author',
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Critical', 'Critical'), ('OS', 'out of stock')], default='PRIV', max_length=23, null=True),
        ),
    ]
